name: bert-pytorch
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python==3.7.*
  - pip
  - numpy
  - tqdm
  - h5py 
  - pytorch
  - pip:
      - tensorboard
      - boto3
      - requests
      - six
      - nltk
      - wikiextractor
      - html2text
      - progressbar
      - git+https://github.com/gpauloski/loggerplus
      - git+https://github.com/NVIDIA/dllogger
      - git+https://github.com/gpauloski/kfac_pytorch@experimental

